<?php

/**
 * @file
 * Provides shipping functionality.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
/*function commerce_shipping_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'commerce_order') {
    $fields['shipment'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Shipment'))
      ->setDescription(t('The shipment object.'))
      ->setSetting('target_type', 'commerce_shipping');

    return $fields;
  }
} */
