commerce_shipping.commerce_shipping_method.*:
  type: config_entity
  label: 'Shipping method'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    configuration:
      type: commerce_shipping.commerce_shipping_method.plugin.[%parent.plugin]

commerce_shipping.commerce_shipping_method.plugin.*:
  type: commerce_shipping_method_configuration

commerce_shipping.commerce_shipping_method.plugin.flat_rate:
  type: commerce_shipping_method_configuration
  mapping:
    rate_label:
      type: label
      label: 'Rate label'
    rate_amount:
      type: field.value.commerce_price
      label: 'Rate amount'

commerce_shipping_method_configuration:
  type: mapping
  mapping:
    default_package_type:
      type: string
      label: 'Default package type'
    services:
      type: sequence
      label: 'Services'
      sequence:
        type: string
